### ISSUE TITLE
enable us-east-2 region 

### ISSUE THREAD

**Issue by StanleyKaleta** [bf2fc6cc711aee1a0c2a/kas-installer#145]
`Error creating Kafka instance 'instance': region eu-central-1 is not supported for aws, supported regions are: [us-east-1]`

Hello, can we get at least another us region enabled, e.g. us-east-2? 

Thanks

**Comment by MikeEdgar** [comment]
@StanleyKaleta - did you set `DATA_PLANE_CLUSTER_REGION` in `kas-installer.env` ? I think that should make it work as you expect.

**Comment by MikeEdgar** [comment]
@StanleyKaleta let me know if you were able to get it working.
