### ISSUE TITLE
Allow for multi cloud provider and multi region support

### ISSUE THREAD

**Issue by machi1990** [bf2fc6cc711aee1a0c2a/kas-installer#158]
Current only one region support is offered and the cloud provider is hardcoded to `aws`.
fleet manager allows the configuration of multiple cloud provider and regions via the SUPPORTED_CLOUD_PROVIDERS: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/70ccf0061089c6938b8ca4e8cb1c17bd42f6c426/templates/service-template.yml#L155 parameter and kas-installer can leverage that to expose support for multi cloud provider and regions.

**Comment by MikeEdgar** [comment]
I think this one is effectively supported now that the parameter customization script is available from #163

**Comment by machi1990** [comment]
Good thinking.
At the moment we are overriding the cluster list and supported cloud providers here: https://github.com/MikeEdgar/kas-installer/blob/542f3f8d443fe4273d8f89ced38e4dcd824744c1/kas-fleet-manager/deploy-kas-fleet-manager.sh#L172-L194

And the parameter customization comes before those two at https://github.com/MikeEdgar/kas-installer/blob/542f3f8d443fe4273d8f89ced38e4dcd824744c1/kas-fleet-manager/deploy-kas-fleet-manager.sh#L159

I wonder if `oc` is clever enough to merge everything. If so and everything works as advertised, then this will be something we might look to add documentation for as well. If not, we might look to tweak things a bit to add multi cloud provider / region support.

**Comment by MikeEdgar** [comment]
> > The challenge will be aligning with CLUSTER_LIST which isn't trivial to just allow to be configured via the custom script.
> 
> Why will this be challenging?

I'm mainly thinking about the `name` being currently aligned with the `KUBE_CONFIG` in the secrets and the `PROVIDER_TYPE` logic a bit earlier in the script. Allowing the `CLUSTER_LIST` to be set directly would require either those to be configurable or to just accept that users have a good knowledge around the requirements of forming a correct `CLUSTER_LIST` within the context of the rest of the script.
