### ISSUE TITLE
Release 0.2.0 release notes

### ISSUE THREAD

**Issue by MikeEdgar** [bf2fc6cc711aee1a0c2a/kas-installer#172]
Mention:
- If set by user, `SUPPORTED_INSTANCE_TYPES` may break due to a new properties
  - https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1029
  - https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1006

**Comment by miguelsorianod** [comment]
Hi @MikeEdgar .

We will soon remove the `KAFKA_LIFE_SPAN` OpenShift template parameter too (and thus the --kafka-lifespan CLI flag too). See https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1042. Specifically,

**Comment by MikeEdgar** [comment]
Closed, release 0.2.0 complete : https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/releases/tag/0.2.0
