### ISSUE TITLE
MANAGEDKAFKA_ADMINSERVER_EDGE_TLS_ENABLED broken

### ISSUE THREAD

**Issue by k-wall** [bf2fc6cc711aee1a0c2a/kas-installer#185]
The intent of `MANAGEDKAFKA_ADMINSERVER_EDGE_TLS_ENABLED` was that it would cause the admin server to be run HTTPs, edge, terminated.  This feature seems to have become broken.

I've not looked why.

You can work around by setting the same env var on the fleetshard subscription.

**Comment by MikeEdgar** [comment]
@k-wall , support for individual envs passed to fleetshard was removed with the move to use KFM as the deployment mechanism for the data plane components. Using the subscription is the correct approach now for things like this.

**Comment by k-wall** [comment]
https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/blob/main/README.md#service-customization documents how it is done.
