### ISSUE TITLE
Changes to support provisioning a Kafka on a dedicated cluster a.k.a enterprise data plane cluster

### ISSUE THREAD

**Issue by machi1990** [bf2fc6cc711aee1a0c2a/kas-installer#266]
- [x] Being able to register the cluster with KFM. We can use the latest release of the rhoas CLI for this.
- [x] Being able to create a Kafka on a dedicated cluster. Once the rhoas CLI supports for this, we can leverage it. 
- [x] Update KFM to latest tag and make sure that KFM is running in OCM mode and not standalone mode when enterprise feature is to be used
- [x] Update the `REGISTERED_USERS_PER_ORGANISATION` to mention grant enterprise quota. See https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/config/quota-management-list-configuration.yaml for the state
- [x] Include the `ENTERPRISE_CLUSTER_REGISTRATION_ALLOWED_ORGANIZATIONS` parameter to enlist allowed orgs for enterprise endpoints. This will be replaced by quota checks. See https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/templates/service-template.yml#L180 for more. This might be replacement with quota checks in the future.
- [x] Update SUPPORTED_INSTANCE_TYPES: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/templates/service-template.yml#L160 for include supported billing models
- [x] Being able to deregister an enterprise cluster

**Comment by machi1990** [comment]
@MikeEdgar

**Comment by machi1990** [comment]
> > make sure that KFM is running in OCM mode and not standalone mode when enterprise feature is to be used
> 
> Do you envision a new flag that indicates whether the user intends to use enterprise features and the installer performs some basic validation and generates an empty `CLUSTER_LIST` based on that?

I was thinking this as well. What do you think?

> > Update SUPPORTED_INSTANCE_TYPES: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/templates/service-template.yml#L160 for include supported billing models
> 
> kas-installer currently just uses the default from the template unless the user intentionally overrides this via a `kas-fleet-manager-service-template-params` script. With the tag update, the default value includes all of the billing types so we may be covered on this out-of-the-box. Thoughts?

+1. So is a quick win. I hope no one overrides the default one in their `kas-fleet-manager-service-template-params` script.

> > Being able to deregister an enterprise cluster
> 
> Are you thinking a wrapper/convenience script or guidance to use `rhoas`?

+1 .I know for a fact that this is a planned work in the CLI, @dimakis can you confirm? So, I think kas-installer needs to only do it after the CLI has support for it. In the meanwhile, the user can directly call the KFM endpoint. What do you think?

**Comment by dimakis** [comment]
> > Are you thinking a wrapper/convenience script or guidance to use `rhoas`?
> 
> +1 .I know for a fact that this is a planned work in the CLI, @dimakis can you confirm? So, I think kas-installer needs to only do it after the CLI has support for it. In the meanwhile, the user can directly call the KFM endpoint. What do you think?

indeed, we do plan on adding a `de-register` command to the CLI 👍

**Comment by MikeEdgar** [comment]
> So, I think kas-installer needs to only do it after the CLI has support for it. In the meanwhile, the user can directly call the KFM endpoint. What do you think?

I don't mind scripting it in the short term. At a minimum, it will give me some hands-on experience with the new endpoint(s) and would be good to have in the `uninstall.sh` process too. It might be good to have a version de-registration available outside of `rhoas` anyway for the un-installation to avoid relying on an active session, etc.

**Comment by machi1990** [comment]
> I don't mind scripting it in the short term. At a minimum, it will give me some hands-on experience with the new endpoint(s) and would be good to have in the `uninstall.sh` process too. It might be good to have a version de-registration available outside of `rhoas` anyway for the un-installation to avoid relying on an active session, etc.

Okay. One thing the script will need to do as well is - remove the AddOns.

**Comment by MikeEdgar** [comment]
> Being able to register the cluster with KFM. We can use the latest release of the rhoas CLI for this.

Based on my understanding of the CLI on the `dedicated` branch, we may be blocked on this until a separate OCM API endpoint can be specified.

**Comment by machi1990** [comment]
> > Being able to register the cluster with KFM. We can use the latest release of the rhoas CLI for this.
> 
> Based on my understanding of the CLI on the `dedicated` branch, we may be blocked on this until a separate OCM API endpoint can be specified.

@dimakis created an alpha release a few weeks ago. Maybe we can have another one with latest changes on https://github.com/redhat-developer/app-services-cli/pull/1804. Any plans on that @dimakis ?

**Comment by dimakis** [comment]
> > > Being able to register the cluster with KFM. We can use the latest release of the rhoas CLI for this.
> > 
> > 
> > Based on my understanding of the CLI on the `dedicated` branch, we may be blocked on this until a separate OCM API endpoint can be specified.
> 
> @dimakis created an alpha release a few weeks ago. Maybe we can have another one with latest changes on [redhat-developer/app-services-cli#1804](https://github.com/redhat-developer/app-services-cli/pull/1804). Any plans on that @dimakis ?

I'm just waiting for someone to approve those changes. As soon as I do I'll release another alpha with the latest changes.

**Comment by MikeEdgar** [comment]
Very nice, I didn't see that PR. I'll at least try to run that locally until there is a release with those changes. Thanks for mentioning it @machi1990 !

**Comment by dimakis** [comment]
> Very nice, I didn't see that PR. I'll at least try to run that locally until there is a release with those changes. Thanks for mentioning it @machi1990 !

there's an alpha release now with the most up to date changes:
```shell
curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash -s v0.52.2-alpha1
```
will grap and install it 👍

**Comment by machi1990** [comment]
> Is it expected that the bootstrap domain does not have the `kas` prefix when CNAME registration is not used? I see in `rhoas` that the `apps` subdomain is removed from the cluster DNS, which means KFM does not replace it with `kas`.

Good catch, that's a bug. `apps.` should be there for the `cluster_dns` when CNAME registration is not used.  /cc @dimakis

**Comment by machi1990** [comment]
@MikeEdgar @dimakis I'll prepare a PR against RHOAS CLI and ping you on it.

**Comment by dimakis** [comment]
> > Is it expected that the bootstrap domain does not have the `kas` prefix when CNAME registration is not used? I see in `rhoas` that the `apps` subdomain is removed from the cluster DNS, which means KFM does not replace it with `kas`.
> 
> Good catch, that's a bug. `apps.` should be there for the `cluster_dns` when CNAME registration is not used. /cc @dimakis

So are there instances of the DNS where the ".apps." Is not in the DNS

**Comment by MikeEdgar** [comment]
> So are there instances of the DNS where the ".apps." Is not in the DNS?

The default ingress for OSD handles the `apps` subdomain, but for MK there are additional subdomains created where `apps` is replaced with `kas`. The current KFM logic just swaps the subdomain (search/replace) so it's expected to be there in the cluster configuration.

**Comment by machi1990** [comment]
@MikeEdgar @dimakis here is an attempt for a fix https://github.com/redhat-developer/app-services-cli/pull/1806 please have a look.

**Comment by machi1990** [comment]
Thanks @MikeEdgar 

all the tasks in this are completed. I’ll close the issue
